### ISSUE TITLE
option to open tool's submenu missing

### ISSUE THREAD

**Issue by staticanimal** [CascadianVR/Auto-Toggle-Creator#4]
i added the tool to project by dragged .unitypackage into my project like the tutorial says but the "Tools>Cascadian>AutoToggleCreator" menu is not showing up.

using unity 2019.4.31f1

**Comment by CascadianVR** [comment]
Hi there!
I just did a test personally and it seems like it's working fine on my end. Do you have any errors in the console or an existing older version you installed over?

**Comment by CascadianVR** [comment]
Actually, looks like I said the wrong thing. It's not under tools and it's under the main top tool bar called "Cascadian"
![image](https://github.com/CascadianVR/Auto-Toggle-Creator/assets/90723146/bec466e0-d132-4c73-8cbd-df29cf2e8928)
